import { loadJSON, storageKeys } from '../core/storage.js';
import { normalizeTierName } from '../services/pricingService.js';
import { normalizeSessionRecord, readPersistedSession } from '../services/authService.js';

function createEmptyCatalog() {
  return {
    companies: [],
    products: [],
    productIndex: {},
    offers: { daily: [], flash: [] },
    tiers: [],
    settings: [],
    settingsMap: {},
    top: { products: [], companies: [] },
    counters: { companies: 0, tiers: 0, deals: 0, flash: 0 },
    catalogProducts: [],
  };
}

export function createInitialState() {
  return {
    app: {
      ready: false,
      route: { name: 'home', params: {} },
      lastError: null,
    },
    ui: {
      search: '',
      drawerOpen: false,
      activeModal: null,
      accountMenuOpen: false,
      selectedProductId: null,
      selectedInvoiceId: null,
      theme: loadJSON(storageKeys.theme, 'vip-light-theme') || 'vip-light-theme',
      toastQueue: [],
      flashTick: Date.now(),
      pendingFlow: null,
      loginFeedback: null,
      customerLocationBusy: false,
      customerLocationError: null,
      customerLocationDraft: {
        text: '',
        lat: null,
        lng: null,
      },
    },
    auth: {
      session: readPersistedSession(),
      selectedCustomer: loadJSON(storageKeys.selectedCustomer, null),
      loginBusy: false,
      registerBusy: false,
      checkoutBusy: false,
    },
    commerce: {
      selectedTier: normalizeTierName(loadJSON(storageKeys.tier, null)),
      unitPrefs: {},
      qtyPrefs: {},
      cart: loadJSON(storageKeys.cart, []),
      catalog: createEmptyCatalog(),
      invoices: [],
      invoiceItemsById: {},
      customers: [],
      top: { products: [], companies: [] },
      priceBook: { tierName: null, products: {} },
    },
    runtime: {
      lifecycle: {
        phase: 'booting',
        locked: true,
        bootId: null,
        error: null,
        sessionRestored: false,
        authorityResolved: false,
        catalogReady: false,
        offersReady: false,
        flashOffersReady: false,
        companiesReady: false,
        pricingReady: false,
        cartSynced: false,
        companyProductsReady: false,
        companyProductsLoading: false,
        companyProductsFailed: false,
        workflowReady: false,
        workflowLoading: false,
        managerReady: false,
      },
      loading: {
        catalog: false,
        company: null,
        customers: false,
        invoices: false,
        manager: false,
        session: false,
        authority: false,
        pricing: false,
        workflow: false,
      },
      pwa: {
        installed: typeof window !== 'undefined' && (
          window.matchMedia?.('(display-mode: standalone)')?.matches
          || window.navigator?.standalone === true
        ),
        installAvailable: false,
        deferredPromptReady: false,
        lastPromptAt: null,
      },
      companyRowsCache: {},
      companyErrors: {},
      workflow: {
        loaded: false,
        loading: false,
        error: null,
        loadedAt: null,
        states: [],
        transitions: [],
        transitionCapabilities: [],
        capabilities: [],
        stateByKey: {},
        transitionsByFromKey: {},
      },
      manager: {
        loaded: false,
        loading: false,
        error: null,
        loadedAt: null,
        ownerId: null,
        module: 'sales-manager',
        teamCustomers: [],
        teamReps: [],
        teamOrders: [],
      },
      ops: {
        runtime: {
          loaded: false,
          loading: false,
          error: null,
          route: 'dashboard',
          routeEntityId: null,
          lastHydratedAt: null,
        },
        catalog: { loaded: false, loading: false, error: null, loadedAt: null, products: [], product: null },
        orders: { loaded: false, loading: false, error: null, loadedAt: null, orders: [], order: null },
        customers: { loaded: false, loading: false, error: null, loadedAt: null, customers: [], customer: null },
        reps: { loaded: false, loading: false, error: null, loadedAt: null, reps: [], rep: null },
        companies: { loaded: false, loading: false, error: null, loadedAt: null, companies: [], company: null },
        reports: { loaded: false, loading: false, error: null, loadedAt: null, summary: null },
        workflows: { loaded: false, loading: false, error: null, loadedAt: null, states: [], transitions: [], transitionCapabilities: [], capabilities: [], stateByKey: {}, transitionsByFromKey: {} },
        hydration: { loadedAt: null },
        guards: { checkoutBlocked: false, checkoutBlockReason: null },
      },
      flashState: null,
      behavior: [],
      splashReady: false,
    },
  };
}
